### ISSUE TITLE
Notify Homeserver of password reset

### ISSUE THREAD

**Issue by hughns** [matrix-org/matrix-authentication-service#110]
After doing https://github.com/matrix-org/matrix-authentication-service/issues/13 the HS needs to be  notified of the reset.

**Comment by hughns** [comment]
Actually it might just be appropriate to notify the HS of the logouts (https://github.com/matrix-org/matrix-authentication-service/issues/111) that the AS has done as a result of the reset.

**Comment by sandhose** [comment]
Standard way to do that would be RISC events: <https://openid.net/specs/openid-risc-event-types-1_0-ID1.html>

**Comment by sandhose** [comment]
We actually now sync the device sessions properly, no need to tell the HS that we reset passwords
