### ISSUE TITLE
How should Client-Service API endpoints that require auth param be handled?

### ISSUE THREAD

**Issue by hughns** [matrix-org/matrix-authentication-service#118]
e.g. https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3keysdevice_signingupload

**Comment by sandhose** [comment]
So in an OIDC world (even with the compatibility layer?), we could drop the first four, plus maybe deleting another device? (which is effectively deleting another session?)

This means we basically only need a solution for: 

 - 3PID bindings
 - cross-signing setup
