### ISSUE TITLE
Feature request: Simplify the setup process

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/matrix-authentication-service#1375]
I have a few comments that I as an server admin notice and can possibly be improved to make it easier for the community to use the module in the future.

I will probably update the ticket in the future.

- [x] currently no tagged versions
- [ ] delivery of built NodeJS files as artifact
- [ ] delivery of built default OPA policy file (policy.wasm)
- [x] prebuild rust binaries similar to Synapse?

Differences in documentation
> Run the server via cargo run -- server -c config.yaml
https://github.com/matrix-org/matrix-authentication-service#running

vs.

> mas-cli server
https://matrix-org.github.io/matrix-authentication-service/usage/usage.html#running

The [official documentation](https://matrix-org.github.io/matrix-authentication-service/) has no infromation about:
- NodeJS
- OPA

**Comment by sandhose** [comment]
The documentation and distribution is definitely lacking. Although it is already in my todo-list to make that better in the next few weeks, contributions on that front is definitely appreciated! Feel free to ask on [#matrix-auth:matrix.org](https://matrix.to/#/#matrix-auth:matrix.org) if something needs to be clarified.

At some point, we were embedding all the assets in the binary, which did not scale well. 

For the record, for ~production, I'm currently relying on the nightly docker images. The Docker image is a good source to know what's needed to run it, outside of the binary itself:

 - `/usr/local/share/mas-cli/assets/` has the built frontend assets
 - `/usr/local/share/mas-cli/manifest.json` is the Vite manifest generated for the frontend
 - `/usr/local/share/mas-cli/templates/` has the `templates/` folder copied as-is
 - `/usr/local/share/mas-cli/policy.wasm` has the OPA policy compiled to WASM

I'm definitely down to publish full archives with both the binary and all the assets.

About publishing versions, I'm not sure when the service will be stable enough to cut a clear version with proper changelogs between versions.

A few questions we would need to answer:

 - which platform+arch are we distributing binaries for? Synapse currently does Linux and macOS, on x86_64, i686 and arm64. I think would skip i686.
 - on Linux, do we build for `glibc` (`{aarch64,x86_64}-unknown-linux-gnu`) based binaries, or do we build fully-static binaries based on `musl` (`{aarch64,x86_64}-unknown-linux-musl`)? Note that in the Docker image we're using `musl` binaries.
 - should we rely on system certificates for root CAs or embed them from webpki in the binary?
 - should we also provide deb/rpm? It looks like it would not be that much more work if we leverage [`cargo-deb`](https://github.com/kornelski/cargo-deb#readme) and [`cargo-generate-rpm`](https://github.com/cat-in-136/cargo-generate-rpm)

**Comment by sandhose** [comment]
I think the documentation is good enough now, and we provide pre-built binaries on releases.
See #1944 as well

https://matrix-org.github.io/matrix-authentication-service/setup/installation.html
