### ISSUE TITLE
Allow user to view and change display name in My Account UI

### ISSUE THREAD

**Issue by hughns** [matrix-org/matrix-authentication-service#1491]

**Comment by kerryarchibald** [comment]
Is there any design for this?

**Comment by hughns** [comment]
> Is there any design for this?

As far as I know, not yet.

**Comment by sandhose** [comment]
Uploading the avatar is really tricky from MAS perspective right now, and we don't have a good way to interact with the regular C-S API from the My Account UI.

To add the required APIs on the MAS side, the quickest way would be to be able to call the C-S API as any user with the admin token MAS has to communicate with Synapse. I opened an issue on their side for this: https://github.com/matrix-org/synapse/issues/16129

**Comment by Johennes** [comment]
I've split off the avatar part into https://github.com/matrix-org/matrix-authentication-service/issues/1542
