### ISSUE TITLE
DM: Set default ordering of sessions to latest active

### ISSUE THREAD

**Issue by kerryarchibald** [matrix-org/matrix-authentication-service#1497]
Latest created sessions should be displayed first.

AC:
- browser sessions, compatibility sessions and oauth2 sessions are ordered by createdAt DESC by default

**Comment by sandhose** [comment]
That's already doable on the backend: instead of paginating forward, with `first: N`, you paginate backwards, with `last: N`

**Comment by pmaier1** [comment]
Blocked by backend currently.
