### ISSUE TITLE
DM: Home page - where you're signed in - browser sessions

### ISSUE THREAD

**Issue by kerryarchibald** [matrix-org/matrix-authentication-service#1503]
Browser sessions are displayed under OAuth2 sessions on the home page

AC:
- Browser sessions are displayed under OAuth2 sessions on the home page
- Subheader for browser sessions
- Latest 5 active browser sessions are displayed
- A 'View all' button follows the list and navigates to `/account/sessions`

**Comment by kerryarchibald** [comment]
@sandhose isn't it important to be able to sign out browser sessions, even when they don't have any oauth/compat sessions?

**Comment by Johennes** [comment]
From an OOB chat with @hughns:

> > Will we require UI support for compatibility sessions for the September release?
> 
> mostly, no. it's what is being used for [element.io](http://element.io/) homeserver
>
> [...]
>
> the "mostly" is that Patrick [...] asked me yesterday about some potential rough edges inside Settings. he and i will look at them together today and see if there is anything to do

**Comment by Johennes** [comment]
Superseded by https://github.com/matrix-org/matrix-authentication-service/issues/1546
