### ISSUE TITLE
DM: Display device type icon

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-authentication-service#1551]
Using the change from https://github.com/matrix-org/matrix-authentication-service/issues/1498, we should show an icon to reflect what device type a session is.

**Comment by sandhose** [comment]
We're missing the "Matrix" API side for this. The client only advertises if its a "web" client or a "native" client but that's it. We need to decide wether we want to introduce a custom/vendor-specific client metadata for this

**Comment by kerryarchibald** [comment]
UI wise: this needs an icon to be added to Compound. I have asked Jano to tidy up the one from EW

**Comment by Johennes** [comment]
> We're missing the "Matrix" API side for this. The client only advertises if its a "web" client or a "native" client but that's it. We need to decide wether we want to introduce a custom/vendor-specific client metadata for this

In the current device manager in EW we [distinguish](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/utils/device/parseUserAgent.ts#L39) between:

* Desktop (Electron)
* Web (including mobile web)
* Mobile (native)
* Unknown

@pmaier1 what granularity do you think we'd need for this?

**Comment by pmaier1** [comment]
I can't see this working in our testing environment. Re-opening.

**Comment by pmaier1** [comment]
Ah, maybe I'm wrong. Is it only expected to be working for native OIDC sessions that were signed in after the change was made? (see screenshot)

![Screenshot from 2023-11-17 09-04-16](https://github.com/matrix-org/matrix-authentication-service/assets/21193500/a82079b9-402c-4cc0-9353-501f37f84244)

Please close if that is the case.

**Comment by kerryarchibald** [comment]
> Is it only expected to be working for native OIDC sessions that were signed in after the change was made?

Yes, other sessions don't have the user agent recorded -> no device type info
