### ISSUE TITLE
Unauthenticated page should link to sign in

### ISSUE THREAD

**Issue by kerryarchibald** [matrix-org/matrix-authentication-service#1617]
<img width="1084" alt="Screenshot 2023-08-28 at 13 52 04" src="https://github.com/matrix-org/matrix-authentication-service/assets/3055605/eba349b5-a293-486e-89ff-fba30e8aba62">

Hitting an /account route while not authenticated shows an error screen but no CTA

AC:
- The 'not logged in' screen should include a link to sign in

**Comment by sandhose** [comment]
So actually this is done by the backend, which means it does not work in "dev" mode.
Two caveats:

 - when signing out the current browser session in the frontend, this page is shown with no way to log back in other than reloading the page
 - this redirect does not keep any query parameters or subpath after login, you will alway be redirected to `/account/`
