### ISSUE TITLE
Sessions from EW show up as "new" instead of "regular"

### ISSUE THREAD

**Issue by Johennes** [matrix-org/matrix-authentication-service#1637]
EW doesn't yet support native OIDC so its sessions should be compatibility ones instead.

**Comment by hughns** [comment]
@Johennes have you been able to reproduce this? Can you share a screenshot if so?

**Comment by Johennes** [comment]
I created this issue off of a remark from @kerryarchibald in our meeting on Tuesday. I haven't actually seen this myself and my own active sessions from EW appear to all be in the "regular" section. @kerryarchibald can you still reproduce this and if so, could you provide more context for @hughns?

**Comment by kerryarchibald** [comment]
I can't reproduce this any more with synapse-oidc.lab.element.dev and develop.element.io

**Comment by Johennes** [comment]
Assuming fixed then.
