### ISSUE TITLE
Improve verification mail wording

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/matrix-authentication-service#1655]
<img width="477" alt="Screenshot 2023-08-30 at 11 39 03" src="https://github.com/matrix-org/matrix-authentication-service/assets/21193500/17370b6d-dc0a-4b3c-bfa2-2de4fcdd8409">

Should change to

- From: ?
- Subject: `Your email verification code is: <confirmation code>`
- Body:

Hello `<display name>` (userid as fallback),

your verification code to confirm this email address is: **`<verification code>`**

**Comment by sandhose** [comment]
The templates are here: https://github.com/matrix-org/matrix-authentication-service/tree/main/templates/emails

They are pretty straight forward to edit. There is one for the HTML version, one for the plain text version, and one for the subject line. I would argue that we should keep the code in the subject line.

Unit tests check that the template renders without errors, so they are pretty safe to edit if someone else wants to do it (@pmaier1 @hughns?)

**Comment by hughns** [comment]
Notes:

- `From:` is set in the config directly
- the display name isn't available because it is coming from Synapse
