### ISSUE TITLE
Custom imprint, privacy policy, terms and conditions

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/matrix-authentication-service#1675]
MAS should offer the ability to configure custom links/input for

- imprint
- info link
- privacy policy link
- terms/conditions link

These should be exposed in the MAS web UI and in the footer of emails sent by MAS.

An example of how this could look in a web footer: (n.b. this isn't supposed to be a proposed design, just representative)

<img width="665" alt="image" src="https://github.com/matrix-org/matrix-authentication-service/assets/6955675/eb5c1e87-6dda-4cb1-a820-c4bd7cbbd259">

**Comment by hughns** [comment]
FTR, I think this requirement is only to show the information and links whereas I have made https://github.com/matrix-org/matrix-authentication-service/issues/1703 to enforce acceptance of terms by the user.

**Comment by sandhose** [comment]
@pmaier1 What are you thinking of for the "imprint"? Where would that show?

**Comment by pmaier1** [comment]
> @pmaier1 What are you thinking of for the "imprint"? Where would that show?

It needs to be shown on all web pages and in the email footer (just as the other ones). I think it is sufficient if we allow configuring a link. If there's no link configured, we wouldn't show it.

**Comment by hughns** [comment]
I think we might want to let people configure different imprints for web vs email which might give some flexibility.

e.g.

- Web footer: All Rights Reserved. The Element name, logo and device are registered trade marks of New Vector Ltd

- Email footer: NOTICE: New Vector Ltd t/a Element is a company registered in England & Wales with company number 10873661. Our registered office is 10 Queen Street Place, London, United Kingdom, EC4R 1AG.


None of these options are mandatory. The default config that is generated by mas-cli can have them as empty values (or omitted entirely).
