### ISSUE TITLE
SSO - Upstream OIDC provider support

### ISSUE THREAD

**Issue by sandhose** [matrix-org/matrix-authentication-service#19]
We should support login via OIDC the same way Synapse does. Hopefully we can skip SAML and CAS for now though

**Comment by sama8** [comment]
If relevant in the future -> [SAML Jackson](https://github.com/boxyhq/jackson)

**Comment by akoyaxd** [comment]
Hello,
is this still on the roadmap?

**Comment by sandhose** [comment]
Actually I don't know why this issue is still open, MAS definitely supports login via upstream OIDC quite well

**Comment by akoyaxd** [comment]
But is it compatible with clients, that are not OIDC aware? So can I use the legacy Element Client to login via OIDC?

**Comment by sandhose** [comment]
Legacy clients still work through a compatibility layer, see https://matrix-org.github.io/matrix-authentication-service/setup/homeserver.html#set-up-the-compatibility-layer

Happy to answer to other questions in [#matrix-auth:matrix.org](https://matrix.to/#/#matrix-auth:matrix.org) or through the [discussion tab](https://github.com/matrix-org/matrix-authentication-service/discussions/categories/q-a)
