### ISSUE TITLE
Password policy option for require_symbol

### ISSUE THREAD

**Issue by hughns** [matrix-org/matrix-authentication-service#2074]
In terms of the actual implementation I suggest that we mimic the [Synapse](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#password_config) `password_config.policy.require_symbol` assuming it is sensible.

**Comment by sandhose** [comment]
We now use zxcvbn with a password strength instead of symbols/lowercase/uppercase/digit/min length options
