### ISSUE TITLE
Improve the session detail view

### ISSUE THREAD

**Issue by sandhose** [matrix-org/matrix-authentication-service#2147]
Currently looks like this:

<img src="https://github.com/matrix-org/matrix-authentication-service/assets/1549952/9bc28d47-03e6-4f67-b8cf-c16d67bed398" width="300" />

[Latest designs](https://www.figma.com/file/HUysJAhv6cK6p1Pc81Fxaa/Matrix-Authentication-Service-(MAS)?type=design&node-id=4350-20939&mode=design&t=umcQytfGtiOIePzE-4)

Note on the implementation: making it a modal might be tricky as we need to be able to deep link to it. A first step would be to implement this in its own page, without a modal.

The scope list should be consistent with what is done on the server-side template for the consent page: https://github.com/matrix-org/matrix-authentication-service/blob/8f96427c47f048b99f44c7deaf5fdcfdcd98cb38/templates/components/scope.html

**Comment by hughns** [comment]
We need a design for this.

**Comment by daniellekirkwood** [comment]
@hughns , do you have a path to design support or do we need to escalate that ?

**Comment by pmaier1** [comment]
Designs here https://www.figma.com/file/HUysJAhv6cK6p1Pc81Fxaa/Matrix-Authentication-Service-(MAS)?type=design&node-id=4344-10620&mode=design&t=fYw0aza1SK7JICbo-4

**Comment by langleyd** [comment]
@t3chguy You mentioned you were blocked on this. I believe you said we didn't have all the data to render the session detail as presented in the designs.

I think it was that device name would be equal to the device id, so that the list would not be actionable for the user. (Similar to this element [web issue](https://github.com/element-hq/element-web/issues/26876)?)

Would you mind confirming so this is actionable for @sandhose ?

**Comment by t3chguy** [comment]
Yes, I believe this was discussed either in the call or in the room, that MAS doesn't have a concept of editable device names at this time, and at the API level it seems that the name for certain session types is entirely unavailable which means that on the frontend the [matrix] Device ID is used instead.

**Comment by sandhose** [comment]
@t3chguy This should be unblocked now that we have more user-agent infos on the sessions. It's not a user-editable session name, but it should be enough to implement something sensible

**Comment by daniellekirkwood** [comment]
there are a couple of PRs here, did we finish this task?

**Comment by t3chguy** [comment]
@daniellekirkwood I think so

Design:
![image](https://github.com/user-attachments/assets/886f401a-6aff-4417-8ff8-3092a4a1232c)

Reality:
![image](https://github.com/user-attachments/assets/f3248cb9-0ba8-4573-a376-32dbd2cff34b)

**Comment by t3chguy** [comment]
Oh the one exception is device names, there's no such concept yet

**Comment by daniellekirkwood** [comment]
thanks! @pmaier1 👀  can we close this out? I don't have permissions... 

If theres furhter support needed from web, feel free to let me know and we can create a new tasks

**Comment by t3chguy** [comment]
I have permissions here to close so will do so, can be re-opened if needed :)
