### ISSUE TITLE
Responsiveness of the MAS UI

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/matrix-authentication-service#2188]
We've seen responsiveness issues on some devices / screen sizes. This should be checked and improved to make sure that the most common devices work fine.

**Example**
![IMG_0010](https://github.com/matrix-org/matrix-authentication-service/assets/21193500/d02d20f5-1b25-467b-aa3f-734ef01d8b11)

**Comment by t3chguy** [comment]
![image](https://github.com/matrix-org/matrix-authentication-service/assets/2403652/4e151495-f02f-4198-8297-7f1b18a9a0d0)

Cannot reproduce this

![image](https://github.com/matrix-org/matrix-authentication-service/assets/2403652/10b7cd56-df26-4157-86cf-5e03ae903b80)
![image](https://github.com/matrix-org/matrix-authentication-service/assets/2403652/4b2b847c-ee53-434f-9b4c-f51dbf2c1e05)

**Comment by yncyrydybyl** [comment]
I have tested it with a iPhone SE with an ios 17.1.2. with Element X 1.5.3 (86).
It is still the case that all MAS screens have a horizontal scroll.

**Comment by langleyd** [comment]
@yncyrydybyl Looks fine on the iPhone SE Simulator for mas.element.io. Do we know what version desil.io is on, in case this has been fixed more recently?

![Image](https://github.com/matrix-org/matrix-authentication-service/assets/6135282/ed347f7a-1260-4daf-8c8e-63bfbb6bb823)

**Comment by t3chguy** [comment]
Closing as cannot reproduce, presumed broken/stale env.
