### ISSUE TITLE
Instance terms of services and privacy policy

### ISSUE THREAD

**Issue by sandhose** [matrix-org/matrix-authentication-service#22]
The user should agree to some terms of services before using the auth service. This aims to replace the existing (broken) `m.login.terms`

**Comment by hughns** [comment]
Also see https://github.com/matrix-org/matrix-authentication-service/issues/1675

**Comment by pmaier1** [comment]
We need to figure out the scope of this and whether versioning + tracking is required or not.

**Comment by sandhose** [comment]
With #2325, we now have an explicit "I agree to the Terms and Conditions" checkbox on registration. This for now records in a table the URL of the T&C the user agreed to, which is enough to keep track of which version each user agreed to.

It is still missing a flow to ask all users to agree to an updated version of the terms, but this is probably good enough for now.
