### ISSUE TITLE
API documenation

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/matrix-authentication-service#2239]
I am missing some docs, which listener offer which endpoints.

- [the code](https://github.com/matrix-org/matrix-authentication-service/blob/main/crates/router/src/endpoints.rs)
- [the listener](https://matrix-org.github.io/matrix-authentication-service/usage/configuration.html#httplisteners)

**Comment by dklimpel** [comment]
Some static GraphQL documentation (showcase):
- https://dklimpel.github.io/matrix-authentication-service/spectaql/
- [code / branch](https://github.com/matrix-org/matrix-authentication-service/compare/main...dklimpel:matrix-authentication-service:test_spectaql)

Using the [playground](https://auth-oidc.lab.element.dev/graphql/playground) or read the [schema](https://github.com/matrix-org/matrix-authentication-service/blob/bd42916309d3237f1523066a6238d520c4cd6f73/frontend/schema.graphql) is not very comftable to get an overview.

related to:
- #2187

**Comment by giomfo** [comment]
The configuration about the HTTP listeners improved a lot:
- The reference documentation lists exhaustively the config options [Configuration file reference - Matrix Authentication Service](https://matrix-org.github.io/matrix-authentication-service/reference/configuration.html#httplisteners) 
- This documentation page talks about how the GraphQL API generally works, and how it has a self-documented schema: [GraphQL API - Matrix Authentication Service](https://matrix-org.github.io/matrix-authentication-service/reference/graphql.html)

thx @sandhose
