### ISSUE TITLE
Separate user and admin APIs

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/matrix-authentication-service#2240]
If I have understood correctly, the graphql API is used by the clients as well as for the administration of MAS itself.

Currently you can't separate admin and client APIs cleanly to avoid exposing admin access to the internet, right?

Administrative access via internet should be prevented via IP filters or similar.
Probably two different graphql entry points are required for this.

**Comment by sandhose** [comment]
We now have a new admin API, which is has its own resource, which can be mounted on a separate listener.

In addition, the GraphQL API is by default only available to the frontend, not for admin purposes, but can still be enabled on a separate listener with the `undocumented_oauth2_access` option set to `true` for admin purposes, for operations that the new admin API doesn't yet have.
