### ISSUE TITLE
Feature: disable user registration

### ISSUE THREAD

**Issue by dklimpel** [matrix-org/matrix-authentication-service#2241]
In a managed environment, I do not want free registration. For this, the self service registration workflow must be able to be deactivated. Admins should still be able to create users.

**Comment by spaetz** [comment]
Same here: I just denied the /register endpoint in my reverse proxy for now. Are there any other possibilities to register a user that I should think of?
Should that be a note in the docs?

**Comment by dklimpel** [comment]
@sandhose Is this realy fixed?

> Admins should still be able to create users.

> Are there any other possibilities to register a user that I should think of?
Should that be a note in the docs?

**Comment by sandhose** [comment]
@dklimpel The feature of being able to disable user registration is indeed done.

Aside from that, currently:

- Users can be created through the `addUser` mutation in the GraphQL API
- Password can be set through the `manage set-password` CLI tool

To make it better, we should also have:

 - https://github.com/matrix-org/matrix-authentication-service/issues/2582
 - https://github.com/matrix-org/matrix-authentication-service/issues/2197

But I consider those to be separate features
