### ISSUE TITLE
'Last activity' in session detail view

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/matrix-authentication-service#2249]
<img width="505" alt="Screenshot 2024-01-10 at 13 43 26" src="https://github.com/matrix-org/matrix-authentication-service/assets/21193500/57bb72f4-6e30-4ae8-9a41-e4461bd6592c">

I think this should be renamed to 'Last activity' and the 'Active' string before the date should be removed.

@sandhose

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/matrix-org/matrix-authentication-service/issues/2147 which has an alternative design where I'll ensure the `Active` prefix doesn't surivive

![image](https://github.com/matrix-org/matrix-authentication-service/assets/2403652/9c6401f6-57b5-4d28-a3cf-8db815720082)
