### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by MomentQYC** [matrix-org/matrix-authentication-service#2358]
Chinese (China, Simplified) translation is now complete
There may be some errors, but the whole should be fine

**Comment by MomentQYC** [comment]
It seems that "Simplified Chinese" and "Chinese (China, Simplified)" are duplicated and can be directly replaced.

**Comment by sandhose** [comment]
Many thanks for your contribution! I did quickly reviewed through reverse-translation and approved most of them. They will be included in the next translation sync in the next release

**Comment by MomentQYC** [comment]
> Many thanks for your contribution! I did quickly reviewed through reverse-translation and approved most of them. They will be included in the next translation sync in the next release

Note that there are some fields that I have improved to make them easier to understand in the Chinese context.
The reason I'm not sure is that I haven't deployed the current version of MAS to confirm which fields correspond to which functions.

**Comment by sandhose** [comment]
So there were a bunch of issues with the language fallback logic. I did move the `zh-CN#Hans` to `zh#Hans` in Localazy as this is the one we use in other projects.
I then made sure that `zh-CN` falls back to `zh#Hans`, which hopefully makes sense.

It should be deployed in a few minutes to the OIDC playground at https://auth-oidc.lab.element.dev if you want to try out

**Comment by MomentQYC** [comment]
> It should be deployed in a few minutes to the OIDC playground at https://auth-oidc.lab.element.dev if you want to try out

I fixed three errors based on what I've seen so far

**Comment by sandhose** [comment]
This happened some time ago. A few keys were added in the meantime, and the Chinese translation hasn't been updated, but I'll close this ticket for now.
