### ISSUE TITLE
Documentation for config settings

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-authentication-service#3]
At some point in the not too distant future, we could do with documentation for the available settings in `config.yaml`. 

Having to go through the exercise of writing the documentation can be quite helpful in making sure that the settings make sense from a user's point of view.

**Comment by sandhose** [comment]
This is now a thing: https://matrix-org.github.io/matrix-authentication-service/usage/configuration.html

Source here: https://github.com/matrix-org/matrix-authentication-service/blob/main/docs/usage/configuration.md

**Comment by sandhose** [comment]
Whilst it is not perfect, the configuration options are now better documented, through the [setup guide](https://matrix-org.github.io/matrix-authentication-service/setup/index.html) as well as the [configuration file reference](https://matrix-org.github.io/matrix-authentication-service/usage/configuration.html)
