### ISSUE TITLE
Consent screen shows wrong Element logo

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/matrix-authentication-service#3037]
<img width="798" alt="Screenshot 2024-07-31 at 16 33 28" src="https://github.com/user-attachments/assets/638a9ddd-bc87-4f8a-a1c5-3e619c167eb4">

**Comment by pmaier1** [comment]
@americanrefugee @amshakal what is the right logo?
@sandhose please change accordingly

**Comment by sandhose** [comment]
This logo is defined by the client, so 🏓 @matrix-org/element-web-team 

What is this screenshot by the way, Figma?

**Comment by t3chguy** [comment]
EW defaults to `/vector-icons/1024.png` e.g. https://app.element.io/vector-icons/1024.png, configurable via config.json though

**Comment by daniellekirkwood** [comment]
I'm led to believe that's the incorrect logo @t3chguy

**Comment by daniellekirkwood** [comment]
Created a web ticket to track the work to fix

**Comment by t3chguy** [comment]
@sandhose does MAS take a copy of the logo at dynamic reg time or will updating it upstream propagate?

**Comment by sandhose** [comment]
It reaches the logo_uri directly, doesn't download/caches it
