### ISSUE TITLE
Polish the crypto identity reset

### ISSUE THREAD

**Issue by sandhose** [matrix-org/matrix-authentication-service#3055]
- Hide the button on the account page under an advanced section
 - Rework the button to make it non-destructive & reword it like "Looking to reset your crypto identity?"
 - Make the page match the design: https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=0-1&t=SzBJoQP4C1n1t6P1-0

**Comment by mxandreas** [comment]
I am trying to make sense if/what is there to be done here on EX side, e.g:

> Rework the button to make it non-destructive & reword it like "Looking to reset your crypto identity?"
Which button? Is it calling out that the implementation does not correspond to what's in Figma or suggesting to change things that are in Figma?

> Make the page match the design
Which page?

**Comment by pmaier1** [comment]
This is not for EX or any other client. It is for pages served by MAS.
