### ISSUE TITLE
Expose password policy on GraphQL

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-authentication-service#3104]
I'm not sure how best to do this since AIUI the polices are dictated by rego files. However, it would be good if we could expose to the UI what the policy is on passwords so real time feedback can be given.

**Comment by sandhose** [comment]
We don't use the OPA policy for passwords anymore, but rather the zxcvbn algorithm, and the minimal complexity is exposed through the GraphQL APi:

```graphql
query {
  siteConfig {
    minimumPasswordComplexity
  }
}
```

**Comment by sandhose** [comment]
Note that @reivilibre did some work so that zxcvbn-ts gave the same result as the Rust crate we use by exporting the dictionaries: https://github.com/matrix-org/matrix-authentication-service/blob/main/frontend/src/utils/password_complexity/index.ts

**Comment by Half-Shot** [comment]
Aha, this is great thank you!
