### ISSUE TITLE
docs for intialising the database

### ISSUE THREAD

**Issue by richvdh** [matrix-org/matrix-authentication-service#4]
It'd be good to include instructions about how to set up the database in the README. I did:

```sh
sudo -u postgres bash
createuser --pwprompt matrix-authentication-service
createdb --encoding=UTF8 --locale=C --template=template0 --owner=matrix-authentication-service matrix-authentication-service
```

... and then set `database.uri` to: `"postgresql://matrix-authentication-service:<password>@localhost/matrix-authentication-service"`

**Comment by sandhose** [comment]
How about some link on how to do that? For example locally I'm running the db in a container, and the official docker image does the user + db creation based on environment variables

Also I forgot to include the database migration: `cargo run -- database migrate`

**Comment by richvdh** [comment]
Also the command to add a new user. I used: `cargo run -- manage register testuser1 testpass1`
