### ISSUE TITLE
i18n/l10n in templates

### ISSUE THREAD

**Issue by sandhose** [matrix-org/matrix-authentication-service#8]
We need to be able to translate all views. This includes HTML templates as well as emails.

Ideally, we'd use something that is well-supported by Weblate and has nice Rust crates for it. We need to be able to embed translations within the binary (like we're doing for static files and templates) as well as loading new ones at runtime to allow customization of templates without recompiling.

**Comment by t3chguy** [comment]
> Ideally, we'd use something that is well-supported by Weblate and has nice Rust crates for it.

We'll be using Localazy instead, we have a lot of flexibility in the format it converts its internal data into. Crates like https://github.com/longbridgeapp/rust-i18n would work fine. Alternatively we could do the i18n in JS client-side. This would allow us to reuse existing tooling from Element Web.
